mutation UpdateTimeCommitmentRange($range: [Int!]) {
  updateTimeCommitmentRange(range: $range) @client
}

mutation UpdateSearchString($search: String!) {
  updateSearchString(search: $search) @client
}

mutation ClearFilter {
  clearFilter @client
}

mutation UpdateLocalGroups($names: [String!]) {
  updateLocalGroups(names: $names) @client
}

mutation UpdateWorkingGroups($names: [String!]) {
  updateWorkingGroups(names: $names) @client
}

mutation UpdateRoleAmount($amount: [Int!]) {
  updateRoleAmount(amount: $amount) @client
}

mutation UpdateRoles($roles: [role]) {
  updateRoles(roles: $roles) @client
}
