query localGroupNames {
  localGroupNames @client
}

query workingGroupNames {
  workingGroupNames @client
}

query getLocalGroupIds($selectedNames: [String!]) {
  local_group(where: { name: { _in: $selectedNames } }) @client {
    id
  }
}

query getWorkingGroupIds($selectedNames: [String!]) {
  working_group(where: { name: { _in: $selectedNames } }) @client {
    id
  }
}

