
type local_group {
  id: Int
  name: string
}

type working_group {
  id: Int
  name: string
}

type Mutation {
  updateLocalGroups(names:[String!]):[local_group!]
  updateWorkingGroups(names:[String!]):[working_group!]
  updateTimeCommitmentRange(range: [Int!]):boolean
}

type Query {
  selectedTimeCommitment: [Int!]
  roleAmount: Int
  searchString: Int
}

schema {
  query: Query
  mutation: Mutation
}