query BoundsTimeCommitmentRange {
  role_aggregate {
    aggregate {
      min {
        time_commitment_min
      }
      max {
        time_commitment_max
      }
    }
  }
}

query Limit {
  limit @client
}

query SearchString {
  searchString @client
}

query SelectedTimeCommitment {
  selectedTimeCommitment @client
}

query Filter @client {
  limit
  searchString
  selectedLocalGroups
  selectedWorkingGroups
  selectedTimeCommitment
}

mutation UpdateTimeCommitmentRange($range: [Int!]) {
  updateTimeCommitmentRange(range: $range) @client
}
