type LocalGroup {
  id: Int
  name: string
}

extend type Mutation {
  updateLocalGroups(names:[String!]): [local_group!]
  updateWorkingGroups(names:[String!]): [working_group!]
  updateTimeCommitmentRange(range: [Int!]): void
  updateRoleAmount(amount: Int!): void
}

extend type Query {
  selectedTimeCommitment: [Int!]!
  roleAmount: Int!
  searchString: String!
  localGroupById(id: Int!): LocalGroup
  navbarHeight: Int!
}

