# queries

query NavbarHeight {
  navbarHeight @client
}

query WorkingGroups {
  working_group {
    id
    name
  }
}

query LocalGroups {
  local_group {
    id
    name
  }
}

query Test($id: Int) {
  getId @client @export(as: "id")
  role(where: { id: { _eq: $id } }) {
    id
    name
  }
}

query Test2 {
  roleData @client {
    filter {
      limit
    }
  }
}

query Test4 {
  getRoleData @client {
    timeCommitmentRange {
      min
      max
    }
  }
  # datap: roleDatap @client
}

# mutations
