fragment RoleFragment on role {
  id
  name
  location
  time_commitment_min
  time_commitment_max
  date_added
  due_date
  local_group {
    name
  }
  working_group {
    name
  }
}

fragment FilterFragment on Filter {
  limit
  searchString
  selectedLocalGroups
  selectedWorkingGroups
  selectedTimeCommitmentMin
  selectedTimeCommitmentMax
}

# queries

query GetRoles(
  $limit: Int
  $search: String
  $localGroupIds: [Int!]
  $workingGroupIds: [Int!]
  $timeCommitmentMin: Int
  $timeCommitmentMax: Int
) {
  RoleData @client {
    filter {
      limit @export(as: "limit")
      searchString @export(as: "search")
      selectedLocalGroups @export(as: "localGroupIds")
      selectedWorkingGroups @export(as: "workingGroupIds")
      selectedTimeCommitmentMin @export(as: "timeCommitmentMin")
      selectedTimeCommitmentMax @export(as: "timeCommitmentMax")
    }
  }
  role(
    where: {
      local_group: { id: { _in: $localGroupIds } }
      working_group: { id: { _in: $workingGroupIds } }
      time_commitment_min: { _gte: $timeCommitmentMin }
      time_commitment_max: { _lte: $timeCommitmentMax }
      name: { _ilike: $search }
    }
    limit: $limit
  ) {
    ...RoleFragment
  }
}

query TimeCommitmentRangeRoles {
  role_aggregate {
    aggregate {
      min {
        time_commitment_min
      }
      max {
        time_commitment_max
      }
    }
  }
}

query GetFilteredRoles {
  getRoleData @client {
    filtered {
      roles {
        ...RoleFragment
      }
    }
  }
}

query GetRoleData {
  RoleData @client {
    filter {
      ...FilterFragment
    }
    timeCommitmentRange {
      min
      max
    }
    calculateTimeCommitmentRange {
      min
      max
    }
    amount
    filtered {
      roles
    }
  }
}

query GetTimeCommitmentRangeRole {
  getRoleData @client {
    timeCommitmentRange {
      min
      max
    }
  }
}

query GetRoleAmount {
  RoleData @client {
    amount
  }
}

query GetFilter {
  RoleData @client {
    amount
    filter {
      ...FilterFragment
      # limit
      # searchString
      # selectedLocalGroups
      # selectedWorkingGroups
      # selectedTimeCommitmentMin
      # selectedTimeCommitmentMax
    }
  }
}

#---------------------------------------------------------------------#

query RoleServerWithFilter($limit: Int) {
  limit @client @export(as: "limit")
  RoleServer(limit: $limit)
}

query RoleServer(
  $limit: Int
  $search: String
  $localGroupIds: [Int!]
  $workingGroupIds: [Int!]
  $timeCommitmentMin: Int
  $timeCommitmentMax: Int
) {
  role(
    where: {
      name: { _ilike: $search }
      local_group: { id: { _in: $localGroupIds } }
      working_group: { id: { _in: $workingGroupIds } }
      time_commitment_min: { _gte: $timeCommitmentMin }
      time_commitment_max: { _lte: $timeCommitmentMax }
    }
    limit: $limit
  ) {
    # ...RoleFragment
    id
    name
    location
    time_commitment_min
    time_commitment_max
    date_added
    due_date
    local_group {
      name
    }
    working_group {
      name
    }
  }
}

query FilteredRoles {
  roleData @client {
    filtered {
      # ...RoleFragment
      id
      name
      location
      time_commitment_min
      time_commitment_max
      date_added
      due_date
      local_group {
        name
      }
      working_group {
        name
      }
    }
  }
}

query RoleDetailServer($id: Int!) {
  role(where: { id: { _eq: $id } }) {
    description
    contact_details
    responsibilities
  }
}

query RoleDetailClient($id: Int!) {
  roleData @client {
    roleDetail(id: $id) {
      ...RoleFragment
      description
      contact_details
      responsibilities
    }
  }
}

query RoleAllInfoServer($id: Int!) {
  role(where: { id: { _eq: $id } }) {
    ...RoleFragment
    description
    contact_details
    responsibilities
  }
}

query RoleData2 {
  roleData @client
}

# query RoleData {
#   RoleData @client {
#     calculateTimeCommitmentRange @client {
#       min @client
#       max @client
#     }
#     timeCommitmentRange {
#       min
#       max
#     }
#   }
# }

query Limit {
  roleData @client {
    filter {
      limit
    }
  }
}

query SearchString {
  roleData @client {
    filter {
      searchString
    }
  }
}

query UpdateFilter {
  roleData @client {
    filter
  }
}

query SelectedTimeCommitment {
  roleData @client {
    filter {
      selectedTimeCommitment
    }
  }
}

query Filter {
  roleData @client {
    filter {
      limit
      searchString
      selectedLocalGroups
      selectedWorkingGroups
      selectedTimeCommitment
    }
  }
}

# query RoleByIdFromCache($id: int!) {
#   role(id: $id) @client {
#     ...RoleFragment
#   }
# }

# mutations

mutation UpdateRoleAmount($amount: [Int!]) {
  updateRoleAmount(amount: $amount) @client
}

mutation UpdateRoles($roles: [role]) {
  updateRoles(roles: $roles) @client
}

query AggregateTimeCommitmentRangeServer {
  role_aggregate {
    aggregate {
      min {
        time_commitment_min
      }
      max {
        time_commitment_max
      }
    }
  }
}

query AggregateTimeCommitmentRangeClient {
  roleData @client {
    timeCommitmentRange {
      min
      max
    }
  }
}

query SelectedLocalGroups {
  roleData @client {
    filter {
      selectedLocalGroups
    }
  }
}

query SelectedWorkingGroups {
  roleData @client {
    filter {
      selectedWorkingGroups
    }
  }
}

query GetRoleLimit {
  RoleData @client {
    amount
    filter {
      limit
    }
  }
}

# mutations

mutation UpdateTimeCommitmentRange($range: [Int!]) {
  roleData @client {
    updateTimeCommitmentRange(range: $range) @client
  }
}

mutation UpdateSearchString($search: String!) {
  updateSearchString(search: $search) @client
}

mutation UpdateLocalGroups($names: [String!]) {
  updateLocalGroups(names: $names) @client
}

mutation UpdateWorkingGroups($names: [String!]) {
  updateWorkingGroups(names: $names) @client
}

mutation ClearFilter {
  clearFilter @client
}
